# Generated by Django 4.2.24 on 2025-09-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du poste')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('requirements', models.TextField(verbose_name='Exigences')),
                ('benefits', models.TextField(verbose_name='Avantages')),
                ('job_type', models.CharField(choices=[('full_time', 'Temps plein'), ('part_time', 'Temps partiel'), ('contract', 'Contrat'), ('internship', 'Stage')], max_length=20, verbose_name="Type d'emploi")),
                ('location', models.CharField(max_length=100, verbose_name='Lieu')),
                ('published', models.BooleanField(default=True, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Carrière',
                'verbose_name_plural': 'Carrières',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(verbose_name='Description courte')),
                ('full_description', models.TextField(verbose_name='Description complète')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Image')),
                ('featured', models.BooleanField(default=False, verbose_name='En vedette')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('client_position', models.CharField(max_length=200, verbose_name='Poste')),
                ('client_company', models.CharField(max_length=200, verbose_name='Entreprise')),
                ('content', models.TextField(verbose_name='Témoignage')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Photo')),
                ('featured', models.BooleanField(default=False, verbose_name='En vedette')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['client_name'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(verbose_name='Extrait')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('client', models.CharField(max_length=200, verbose_name='Client')),
                ('industry', models.CharField(max_length=100, verbose_name='Secteur')),
                ('challenge', models.TextField(verbose_name='Défi')),
                ('solution', models.TextField(verbose_name='Solution')),
                ('results', models.TextField(verbose_name='Résultats')),
                ('image', models.ImageField(blank=True, null=True, upload_to='case_studies/', verbose_name='Image')),
                ('featured', models.BooleanField(default=False, verbose_name='En vedette')),
                ('published_date', models.DateField(verbose_name='Date de publication')),
                ('services', models.ManyToManyField(blank=True, to='sanabaweb.service', verbose_name='Services associés')),
            ],
            options={
                'verbose_name': 'Étude de cas',
                'verbose_name_plural': 'Études de cas',
                'ordering': ['-published_date'],
            },
        ),
    ]
