# Generated by Django 4.2.24 on 2025-09-16 22:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanabaweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='full_description',
            field=ckeditor.fields.RichTextField(verbose_name='Description complète'),
        ),
    ]
